// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAno30DGOf0FRdlDKpqYBIoYoa2vz5DQcY',
    appId: '1:1041627080191:web:6cb0cab94df2b915bdf3ca',
    messagingSenderId: '1041627080191',
    projectId: 'loginsinguptest1',
    authDomain: 'loginsinguptest1.firebaseapp.com',
    storageBucket: 'loginsinguptest1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYomXevplNK-98MVAHG0WpXC2x_jisdzw',
    appId: '1:1041627080191:android:43a49fdd462c1e48bdf3ca',
    messagingSenderId: '1041627080191',
    projectId: 'loginsinguptest1',
    storageBucket: 'loginsinguptest1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3u-RtVRd7k7RkCLdw6PIutPBkxScToAw',
    appId: '1:1041627080191:ios:d82f86322c928eeabdf3ca',
    messagingSenderId: '1041627080191',
    projectId: 'loginsinguptest1',
    storageBucket: 'loginsinguptest1.appspot.com',
    iosClientId: '1041627080191-ni4ro6d1avgrlpnrfn01srnv998osv0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3u-RtVRd7k7RkCLdw6PIutPBkxScToAw',
    appId: '1:1041627080191:ios:d82f86322c928eeabdf3ca',
    messagingSenderId: '1041627080191',
    projectId: 'loginsinguptest1',
    storageBucket: 'loginsinguptest1.appspot.com',
    iosClientId: '1041627080191-ni4ro6d1avgrlpnrfn01srnv998osv0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignup',
  );
}
